os: linux
dist: xenial
language: python

python:
   - 3.6  # Minimum
   - 3.8

addons:
  apt:
    packages:
      - gnuplot

cache: pip

notifications:
  email: false

before_install:
   - gnuplot --version

install:
   - pip install ipykernel metakernel
   - pip install --upgrade pytest>=3.0.6
   - pip install pytest-cov
   - pip install coveralls
   - python setup.py install
   - pip list

script:
   - make test

after_success:
   - coveralls --rcfile=.coveragerc
